### PR TITLE
Little Frog Game

### PR DESCRIPTION
**Pull request by tabreturn**
# New Port for Little Frog Game

## Game Information
- **Title**: Little Frog Game
- **URL**: https://jamphibious.itch.io/little-frog-game

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [x] JELOS

### Resolution Tests
Test all major resolutions:
- [x] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [ ] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - Port Name.sh
    - portname/
      - <portfiles here>
      -

### CODE REVIEW

**Review by Cebion — APPROVED** [review]
👍

**Review by Cebion — CHANGES_REQUESTED** [review]
Error: Bad port name 'Little Frog Game.zip', recommended name is 'little.frog.game.zip'
Error: No port directory named little.frog.game. Main port directory needs to be named little.frog.game
Changes:
  New:       1
  Broken:    2
  Updated:   2
  Unchanged: 337

Total Ports: 342
Error: Process completed with exit code 255.

**Review by kloptops — APPROVED** [review]
👍

**Review by Cebion — APPROVED** [review]
👍

**Pull request merged**
