### PR TITLE
Update Descent 2 port

### PR DESCRIPTION
**Pull request by JeodC**
# Update for Descent 2

## Changelog
- Change `lib` to `libs`
- Add soundfont (remove dxa for user preference)
- Add libmodplug for some JelOS builds
- Sync port to latest from old PortMaster repo
- Remove log.txt generation since game generates gamelog.txt in `conf` folder
- Update readme

### CODE REVIEW

**Review by Cebion — DISMISSED** [review]
Approved after review

**Review by Tekkenfede — CHANGES_REQUESTED** [review]
you forgot to remove  2>&1 in the launch command ( ./$GAME -hogdir data 2>&1 ). 
Beside that, all good

**Comment by JeodC** [comment]
> you forgot to remove 2>&1 in the launch command ( ./$GAME -hogdir data 2>&1 ). Beside that, all good

Fixed, thanks for noticing.

**Review by Tekkenfede — APPROVED** [review]
Approved

**Review by Cebion — APPROVED** [review]

**Pull request merged**
