### PR TITLE
doom3 - rebuild from latest d3es-multithread upstream

### PR DESCRIPTION
**Pull request by porschemad911**
# Updated Port for Doom 3

## Game Information
- **Title**: Doom 3
- **URL**: https://github.com/emileb/d3es-multithread

## Testing
Testing: https://discord.com/channels/1122861252088172575/1200409261986021567

Changes:

- recompiled in Ubuntu Focal Docker container against https://github.com/emileb/d3es-multithread/commit/4f35e6ad2acafb936b784a9d33c8383864ce91a8
- updates to `Doom 3.sh` as per PortMaster docs
- added build instructions to README.md
- added licence
- clean up unneeded files

### CODE REVIEW

**Review by JeodC — APPROVED** [review]
Looks good.

**Comment by porschemad911** [comment]
Sorry @JeodC pushed another commit to move the licence files into the correct folder - the check run failed with:

```
2024-02-05T01:15:42.9702807Z ##[warning]Unknown file: LICENCE.txt
2024-02-05T01:15:42.9712255Z ##[warning]Unknown file: COPYING.txt
```

**Comment by porschemad911** [comment]
Some more tidy-ups required due to PortMaster repo migration leaving files from old version of port. Done now and ready for review.

**Review by Cebion — APPROVED** [review]
Good job, looks good

**Review by kloptops — APPROVED** [review]
👍

**Pull request merged**
