### PR TITLE
- Update README.md

### PR DESCRIPTION
**Pull request by tabreturn**
See "Extras" section here (which has a Shovel Knight listing) http://portmaster.games/detail.html?name=undertale

I removed the folder structure seeing the Undertale port isn't complicated, anyhow.

### CODE REVIEW

**Review by Slayer366 — APPROVED** [review]

**Comment by kloptops** [comment]
This was only added this week to avoid confusion.l and so that people can see what the layout is expected to be.

**Comment by tabreturn** [comment]
> This was only added this week to avoid confusion.l and so that people can see what the layout is expected to be.

Should I add the actual Undertale directory structure instead?

**Comment by kloptops** [comment]
Actually yeah I put it in the wrong readme. My bad. 🤦‍♂️

**Review by kloptops — APPROVED** [review]
👍

**Pull request merged**
