### PR TITLE
Wizard Orb

### PR DESCRIPTION
**Pull request by tabreturn**
# New Port for Wizard Orb

## Game Information
- **Title**: Wizard Orb
- **URL**: https://slimewitch.itch.io/wizard-orb

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [ x JELOS

### Resolution Tests
Test all major resolutions:
- [x] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [ ] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - Port Name.sh
    - portname/
      - <portfiles here>

### CODE REVIEW

**Review by kloptops — APPROVED** [review]
👍

**Review by Cebion — DISMISSED** [review]
👍

**Comment by kloptops** [comment]
Looks like you either need to rename the top level port directory, or the port directory. They don't match.

It should either be:
`ports/wizard.orb/wizard.orb/`
or:
`ports/wizardorb/wizardorb/`

😄

**Review by kloptops — APPROVED** [review]
👍

**Review by Cebion — APPROVED** [review]

**Pull request merged**
