### PR TITLE
openomf - compile updated binary, fix gptokeyb mappings and remove log.txt

### PR DESCRIPTION
**Pull request by porschemad911**
Tested on my Odroid Go Ultra and Game Consoie R33S, both running JELOS

### CODE REVIEW

**Comment by porschemad911** [comment]
Draft for now, needs testing on some other devices

**Comment by porschemad911** [comment]
Testing thread: https://discord.com/channels/1122861252088172575/1209828793074720808

**Comment by porschemad911** [comment]
Updated gptokeyb mappings to match default 'Right keyboard' control scheme, now works OOTB. Made script and binary executable and cleaned up superfluous gamedata files as per https://github.com/omf2097/openomf/blob/master/INSTALL.md#data-files

**Review by Cebion — APPROVED** [review]
Testing on all Required devices done.

**Pull request merged**
