### PR TITLE
Stop the Egg Express

### PR DESCRIPTION
**Pull request by monkeyx-net**
# New Port for  Stop the Egg Eggspress

## Game Information
- **Title**: Stop the Egg Eggspress 
- **URL**: https://stephensmith.itch.io/stop-the-eggspress

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [x] JELOS

### Resolution Tests
Test all major resolutions:
- [x] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

### CODE REVIEW

**Comment by Cebion** [comment]
You have to fill out the Port Template too :P

**Review by Cebion — CHANGES_REQUESTED** [review]
- .sh script has a Typo Exgpress
- Screenshot needs to be in 640x480
- The controls also go into the README.md We have also a generator for that
https://portmaster.games/port-markdown.html

Beside that looks good!

**Comment by monkeyx-net** [comment]
> You have to fill out the Port Template too :P

Does that get auto generated when you create the pull request?

**Comment by monkeyx-net** [comment]
> * .sh script has a Typo Exgpress
> 
>     * Screenshot needs to be in 640x480
> 
>     * The controls also go into the README.md We have also a generator for that
>       https://portmaster.games/port-markdown.html
> 
> 
> Beside that looks good!

Thanks will make the changes

**Comment by monkeyx-net** [comment]
Removed the extra port

**Comment by Cebion** [comment]
Is it Stop the Egg Eggspress or Stop the Eggspress?
If the later also don't forget to rename the port.json entry

**Comment by monkeyx-net** [comment]
https://github.com/fabiangreffrath/jumpnbump

**Pull request closed without merging**
