### PR TITLE
New Port: Bootleg Box

### PR DESCRIPTION
**Pull request by Jareth247**
# New Port for Bootleg Box

## Game Information
- **Title**: Bootleg Box
- **URL**: https://hwilson.itch.io/bootleg-box-01

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [X] AmberELEC
- [X] ArkOS
- [X] JELOS

### Resolution Tests
Test all major resolutions:
- [X] 480x320
- [X] 640x480
- [X] 720x720 (RGB30)
- [X] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

### CODE REVIEW

**Comment by Jareth247** [comment]
Forgot License. Adding it now.

**Review by Cebion — CHANGES_REQUESTED** [review]
Please add source of the game to the README

Either Source: 
or Gameurl: something like that.

Currently only a link to the creators page is there.

**Comment by Jareth247** [comment]
> > Please add source of the game to the README
> > Either Source: or Gameurl: something like that.
> > Currently only a link to the creators page is there.
> 
> Okay. And if I made the same mistake with my other readme files I'll fix them ASAP.

So it turns out I do have to fix the other readme files. Can I put them as the same pull request or do I have to file a separate pull request for each?

**Comment by Cebion** [comment]
> > > Please add source of the game to the README
> > > Either Source: or Gameurl: something like that.
> > > Currently only a link to the creators page is there.
> > 
> > 
> > Okay. And if I made the same mistake with my other readme files I'll fix them ASAP.
> 
> So it turns out I do have to fix the other readme files. Can I put them as the same pull request or do I have to file a separate pull request for each?

You can do them in one PR =)

**Review by Cebion — APPROVED** [review]

**Review by kloptops — APPROVED** [review]
👍

**Pull request merged**
