### PR TITLE
Pm cavebuster

### PR DESCRIPTION
**Pull request by onionland**
# New Port for { Cave Buster }

## Game Information
- **Title**: { Cave Buster }
- **URL**: { https://jontopielski.itch.io/cave-buster }

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [x] JELOS

### Resolution Tests
Test all major resolutions:
- [x] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

### CODE REVIEW

**Review by JeodC — CHANGES_REQUESTED** [review]
```
Error: Missing README.md.
Error: Missing screenshot.{png|jpg}.
Error: Missing port.json.
```

1. You don't have a README.md file: https://portmaster.games/port-markdown.html
2. Your ports.json is in ports/cavebuster/cavebuster, put it in ports/cavebuster
3. Same with your screenshot

**Comment by JeodC** [comment]
Nope, you need to make it .zip:

```json
{
  "version": 2,
  "name": "cavebuster.zip",
  "items": [
    "Cave Buster.sh",
    "cavebuster"
  ],
  "items_opt": [],
  "attr": {
    "title": "Cave Buster",
    "porter": [
      "Consumerism"
    ],
    "desc": "Play as a little alien guy who crash landed into the core of a dangerous planet.  Make your way through fiery caverns and alien fauna.  Find the super duper Burger and eat it!",
    "inst": "1.Download 1 of the zip files from https://jontopielski.itch.io/cave-buster\n2. Copy the \"**.pck\" file from your downloaded zip into the gamedata folder of the cavebuster folder in your ports. Then rename it to \"cavebuster.pck\".",
    "genres": [
      "platformer"
    ],
    "image": null,
    "rtr": false,
    "exp": false,
    "runtime": null,
    "reqs": []
  }
}
```

**Comment by onionland** [comment]
Oh I must have misunderstood, I thought we switched away from zips?

**Comment by JeodC** [comment]
> I'm sorry, I still fail to understand what it is I'm supposed to do, if portmaster-release grabs the files from here and zips them why am I supposed to zip them before submitting them here? Or do you mean there is a tag I have missed somewhere?

You're supposed to add the .zip name in port.json as the example I commented earlier. You don't actually zip the files--that's done via scripts.

**Comment by onionland** [comment]
Ah I see, I was unaware the extension was supposed to be included

**Review by Cebion — APPROVED** [review]
👍

**Review by JeodC — APPROVED** [review]
Looks good.

**Pull request merged**
