### PR TITLE
Create supergaelicdodgeball

### PR DESCRIPTION
**Pull request by zehmaluco**
# New Port for { Super Gaelic Dodgeball }

## Game Information
- **Title**: { Super Gaelic Dodgeball }
- **URL**: { https://shoehead.itch.io/sgdb }

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [ x] AmberELEC
- [ x] ArkOS
- [ x] ROCKNIX
- [ x] muOS

### Resolution Tests
Test all major resolutions:
- [x ] 480x320
- [x ] 640x480
- [x ] 720x720 (RGB30)
- [x ] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - gameinfo.xml
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

[supergaelicdodgeball.zip](https://github.com/user-attachments/files/16648431/supergaelicdodgeball.zip)

### CODE REVIEW

**Comment by kloptops** [comment]
Whats going on here? There's no port files, or anything except the gameinfo.xml file?

**Comment by zehmaluco** [comment]
[supergaelicdodgeball.zip](https://github.com/user-attachments/files/16647997/supergaelicdodgeball.zip)

My bad, this is my first time using github. I've attached the files, is this correct now?

**Comment by Slayer366** [comment]
> My bad, this is my first time using github. I've attached the files, is this correct now?
> 
> [supergaelicdodgeball.zip](https://github.com/user-attachments/files/16648429/supergaelicdodgeball.zip)

You'll need to unpack everything in this zip file and upload all of those on your GH repo like you did with the file that's here, except that the 'ports/supergaelicdodgeball' file you have here should be in a subfolder with the same name and that file should be renamed to gameinfo.xml since that file contains the scrape information for the game.  Make sure your folder structure matches when decompressing everything from your zip archive.

**Comment by zehmaluco** [comment]
Hey guys. Can we delete this PR? I figured ou what I did wrong and made a new PR with the proper files.

**Pull request closed without merging**
