### PR TITLE
Fix sway fullscreen on some ports

### PR DESCRIPTION
**Pull request by sydarn**
# Fix full screen on sway on some ports

SorR, sonic2013 and OpenJazz.

Tested SorR, but I know the other 2 have the same issue and likely more ports, that will have to be addressed later...

### CFW Tests
- [x ] ROCKNIX

### CODE REVIEW

**Comment by sydarn** [comment]
There may very well be other ways the apps natively can request fullscreen, but don't. So there may be other ways to fix this issue...

**Comment by sydarn** [comment]
I am drafting this PR, we are trying to examiate if there are more or better options to do this. If you have an idea of how the ports themselves can request through SDL or something, I can test that too.

Leaving the PR open for debate.

**Comment by sydarn** [comment]
Undrafted, we hopefully get a cleaner solution down the road. But for the time being, to get the ports running, we'd like to merge this from ROCKNIX behalf.

**Review by kloptops — APPROVED** [review]
Looks good. 👍

**Pull request merged**
