### PR TITLE
New Port: Galaxy Forces 2

### PR DESCRIPTION
**Pull request by monkeyx-net**
# Galaxy Forces 2

## Game Information
- **Title**: Galaxy Forces 2
- **URL**:https://sourceforge.net/projects/galaxyv2/ 

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x ] AmberELEC
- [ x] ArkOS
- [ x] JELOS

### Resolution Tests
Test all major resolutions:
- [ x] 480x320
- [ x] 640x480
- [ x] 720x720 (RGB30)
- [x ] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

### CODE REVIEW

**Review by kloptops — APPROVED** [review]
looks good. 👍

**Comment by Cebion** [comment]
Where does this file come from?
https://github.com/PortsMaster/PortMaster-New/blob/e3b86c0bddb632f1b1a42b8de6b3c7f94242bb9a/ports/galaxyforcesv2/galaxyforcesv2/Assets/Images/screenshot.png

**Comment by monkeyx-net** [comment]
I think that is a test image from my imgui app!


Cell +44 7734309500

Work hard in silence, let your success be your noise.

**Comment by monkeyx-net** [comment]
I have removed two images that are not needed from the imgui front end

**Review by Cebion — APPROVED** [review]

**Review by kloptops — APPROVED** [review]
👍

**Pull request merged**
