### PR TITLE
New Port: Oquonie

### PR DESCRIPTION
**Pull request by Cebion**
# New Port for Oquonie

## Game Information
- **Title**: Oquonie
- **URL**: https://hundredrabbits.itch.io/oquonie

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [X] AmberELEC
- [X] ArkOS
- [x] JELOS

### Resolution Tests
Test all major resolutions:
- [X] 480x320
- [X] 640x480
- [X] 720x720 (RGB30)
- [X] Higher resolutions (e.g., 1280x720)

### CODE REVIEW

**Review by tabreturn — DISMISSED** [review]
Looks good. 

Haha -- I quite liked the itch.io description, *The game was best described as "Animal Crossing in a K-Hole."*

**Review by kloptops — CHANGES_REQUESTED** [review]
Screenshot is wrong resolution.

**Review by tabreturn — APPROVED** [review]
Revised image is indeed 640 x 480 pixels

**Review by kloptops — APPROVED** [review]
👍

**Pull request merged**
