### PR TITLE
Add new port Sunset Witch Classic

### PR DESCRIPTION
**Pull request by JeodC**
# New Port for Sunset Witch Classic

## Game Information
- **URL**: https://angusbeer.itch.io/sunset-witch-classic

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [x] AmberELEC
- [x] ArkOS
- [x] JELOS

### Resolution Tests
Test all major resolutions:
- [x] 480x320
- [x] 640x480
- [x] 720x720 (RGB30)
- [x] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

### CODE REVIEW

**Review by Cebion — CHANGES_REQUESTED** [review]
README.md needs Credits to the original author and a link to the Source.
Example: 

Thanks to [Błażej Szczygieł](https://github.com/zaps166/NFSIISE) for creating this wrapper and making it available for free!

**Comment by JeodC** [comment]
> README.md needs Credits to the original author and a link to the Source. Example:
> 
> Thanks to [Błażej Szczygieł](https://github.com/zaps166/NFSIISE) for creating this wrapper and making it available for free!

AngusBeer is listed in the README and the user must download the game from the source themselves.

**Comment by Cebion** [comment]
Won't get merged unless a proepr credit is inserted. Sorry

**Review by Cebion — APPROVED** [review]

**Review by kloptops — APPROVED** [review]
👍

**Pull request merged**
