### PR TITLE
New Port: Star vs the Game

### PR DESCRIPTION
**Pull request by Cebion**
# New Port for Star vs the Game

## Game Information
- **Title**: Star vs the Game
- **URL**: https://rian-shinozaki.itch.io/star-vs-the-game

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [X] AmberELEC
- [X] ArkOS
- [X] JELOS

### Resolution Tests
Test all major resolutions:
- [X] 480x320
- [X] 640x480
- [X] 720x720 (RGB30)
- [X] Higher resolutions (e.g., 1280x720)

## File Structure
- Your port should have the following structure:
  - portname/
    - port.json
    - README.md
    - screenshot.jpg
    - cover.jpg
    - Port Name.sh
    - portname/
      - <portfiles here>

## Additional Resources
For an in-depth guide on creating a pull request, refer to: [PortMaster Game Packaging Guide](https://portmaster.games/packaging.html#creating-a-pull-request)

### CODE REVIEW

**Review by kloptops — DISMISSED** [review]
👍

**Review by tabreturn — COMMENTED** [review]
JSON "title" should be "Star vs. the Game" -- (see dot to abbreviate vs. https://rian-shinozaki.itch.io/star-vs-the-game)

I know! Pedantic ...

**Review by JeodC — CHANGES_REQUESTED** [review]
```
JSON "title" should be "Star vs. the Game" -- (see dot to abbreviate vs. https://rian-shinozaki.itch.io/star-vs-the-game)

I know! Pedantic ...
```

**Review by JeodC — APPROVED** [review]
I'll allow it.

**Review by kloptops — APPROVED** [review]
😎

**Pull request merged**
