### PR TITLE
New Port: Apotris

### PR DESCRIPTION
**Pull request by Cebion**
# New Port for Apotris

## Game Information
- **Title**: Apotris
- **URL**: https://gitea.com/akouzoukos/apotris

### CFW Tests
Ensure your game has been tested on all major CFWs:
- [X] AmberELEC
- [X] ArkOS
- [X] JELOS

### Resolution Tests
Test all major resolutions:
- [X] Higher resolutions (e.g., 1280x720)
- [X] 480x320
- [X] 640x480
- [X] 720x720 (RGB30)

### CODE REVIEW

**Review by kloptops — CHANGES_REQUESTED** [review]
Warning: Unknown file: apotris.port.json
Error: No ports/apotris/port.json file found, found ports/apotris/apotris.port.json as a possible candidate.

Looks like `tools/build_release.py` isnt reporting an error.

**Review by kloptops — DISMISSED** [review]
👍

**Review by JeodC — CHANGES_REQUESTED** [review]
`rtr` tag needs to be set to true in json assuming game is truly Ready to Run

**Review by JeodC — APPROVED** [review]
This pleases me.

**Pull request merged**
