### PR TITLE
[cave.story-evo] Update binaries, fix controls

### PR DESCRIPTION
**Pull request by octopuserectus**
Compiled the latest version, added GPTOKEYB mapping, rewrote startup script

### CODE REVIEW

**Comment by octopuserectus** [comment]
Should fix #115

**Review by JeodC — CHANGES_REQUESTED** [review]
The launhscript is missing `source $controlfolder/device_info.txt` which is where thw $CFW_NAME variable comes from.

**Review by JeodC — APPROVED** [review]
Looking good

**Review by Cebion — APPROVED** [review]

**Comment by wwark** [comment]
For RGB30, the video mode 720x720 is not present anymore with this commit.

**Pull request merged**
